### ISSUE TITLE
최완선 학생 자기소개에서 resume링크 접속이 안됩니다

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/aiml-k.github.io#12]
https://aiml-k.github.io/author/wanshan-cui/ 

의 내용 중 아래 링크 따라가보면 

<img width="839" alt="image" src="https://github.com/AIML-K/aiml-k.github.io/assets/55645287/d8396f2f-c211-466a-8529-dca79442bd7f">

권한이 없어요

<img width="625" alt="image" src="https://github.com/AIML-K/aiml-k.github.io/assets/55645287/a4a6de08-5de7-4593-896b-4ccb260484bb">

**Comment by d-h-lee** [comment]
해결책 제안: 구글 드라이브에서 access를 everyone-view로 바꾸면 됩니다. 아마 링크가 바뀔수도 있으니, 그렇다면 업데이트 필요!

**Comment by choi430** [comment]
말씀하신 대로 구글 드라이브에서 설정 변경하였고, 해당 하이퍼링크 접속 확인했습니다.
감사합니다~
